### ISSUE TITLE
[HOMEWORK] woc1111 的 Java 作业提交

### ISSUE THREAD

**Issue by 9vvert** [sast-summer-training-2024/sast2024-java#1]
这是我完成的作业仓库地址：[woc1111/sast2024-java](https://github.com/woc1111/sast2024-java)。

我在提交前完成了以下检查：
- [x] 已通过自己仓库中的 GitHub Actions。
- [x] 将此 Issue 的标题中的 `YourName` 换为自己的 GitHub 用户名。
- [x] 将此 Issue 的正文中的 `YourName/RepoName` 换为自己的 GitHub 仓库，并将后面超链接链接至自己的作业仓库。
- [x] 此表格中的所有选项均已完成。

**Comment by leverimmy** [comment]
LGTM! 感觉没有任何问题！非常棒！
